export const PANEL_VIEW_TYPE = 'agentPanel';
export const COMMAND_OPEN = 'agentPanel.open';
export const COMMAND_NEW_TERMINAL = 'agentPanel.newTerminal';
export const COMMAND_CLOSE_TERMINAL = 'agentPanel.closeTerminal';
export const COMMAND_FOCUS_NEXT = 'agentPanel.focusNext';
export const COMMAND_FOCUS_PREV = 'agentPanel.focusPrev';
export const COMMAND_FOCUS_UP = 'agentPanel.focusUp';
export const COMMAND_FOCUS_DOWN = 'agentPanel.focusDown';
export const COMMAND_FOCUS_LEFT = 'agentPanel.focusLeft';
export const COMMAND_FOCUS_RIGHT = 'agentPanel.focusRight';
export const COMMAND_OPEN_VSCODE_TERMINAL = 'agentPanel.openVscodeTerminal';
export const COMMAND_OPEN_EXPLORER = 'agentPanel.openExplorer';
export const COMMAND_DELETE_WORD_BACK = 'agentPanel.deleteWordBack';
export const EXTENSION_ID = 'agent-panel';
export const SESSION_STORAGE_KEY = 'agentPanel.sessions';
export const RATE_LIMIT_CACHE_TTL = 60_000; // 60秒
